# Site settings
title: BlogTalks | 4 weeks training blog
description: "A static blog page, build with Jekyll."
url: "https://jaswantsinghh.github.io/BlogTalks/"
author:
  name: "Jaswant Singh"
  email: "jaswantgndec@gmail.com"
  url: "https://jaswantsinghh.github.io/BlogTalks/"

# Build settings
baseurl: /BlogTalks/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false
